// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc78tyzwyV5kkfJl9S7eFkrfHphgw6bMM',
    appId: '1:705236274749:web:d2f806660a913d2d012454',
    messagingSenderId: '705236274749',
    projectId: 'smart-queue-app-7d418',
    authDomain: 'smart-queue-app-7d418.firebaseapp.com',
    storageBucket: 'smart-queue-app-7d418.firebasestorage.app',
    measurementId: 'G-25XDQQ8X0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChNEjX1Or8M7IG1r-6N-Qy0tjqulQf-tU',
    appId: '1:705236274749:android:5357004fdb1cc782012454',
    messagingSenderId: '705236274749',
    projectId: 'smart-queue-app-7d418',
    storageBucket: 'smart-queue-app-7d418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTqlDpigmF7uP9oXexLIe-5VzU4MpYMKI',
    appId: '1:705236274749:ios:f444812ad7b39988012454',
    messagingSenderId: '705236274749',
    projectId: 'smart-queue-app-7d418',
    storageBucket: 'smart-queue-app-7d418.firebasestorage.app',
    iosBundleId: 'com.example.smartQueueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc78tyzwyV5kkfJl9S7eFkrfHphgw6bMM',
    appId: '1:705236274749:web:07e99d8bcb3096bd012454',
    messagingSenderId: '705236274749',
    projectId: 'smart-queue-app-7d418',
    authDomain: 'smart-queue-app-7d418.firebaseapp.com',
    storageBucket: 'smart-queue-app-7d418.firebasestorage.app',
    measurementId: 'G-YLRSBNTWKS',
  );
}
